version: '3.7'

services:
  wordpress:
    build:
      context: ./tests
      args:
        WP_TAG: wordpress:${WP_TAG}
    restart: always
    ports:
      - ${WP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_SKIP_INSTALL: 'yes'
    volumes:
      - ./:/var/www/html/wp-content/plugins/kadence-blocks
    depends_on:
      - db

  db:
    image: mariadb:10.5
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
